Updated CheckRoot() and LocalOrSsh().

diff --git a/system-info b/system-info
--- a/system-info
+++ b/system-info
@@ -106,19 +106,37 @@ function CheckRoot()
     if [[ "$EUID" == 0 ]] || [ $UID -eq 0 ]
     then 
         echo -e "$redback Do not run this script with sudo or as root$resetvid"
+        echo -e "If your Linux ditribution installs with only a Root User as a default, "
+        echo -e "please create another User that has the ability to run elevated commands. "
+        Pause
         exit_code=106
         exit $exit_code
     else
         echo -e "This script needs some parts of it to run with elevated permissions."
-        echo -e "Please enter your password for that to happen."
-        sudo -k # revoke previously cached sudo password 
-        if sudo true
-        then 
-            echo "Running Script: ${sname} $version"
-        else 
-            echo "Password was incorrect for sudo elevated rights. Exiting Script."
-            exit_code=107
-            exit $exit_code
+        nl
+        ## Check if 'sudo' is installed...
+        if type sudo > dev/null 2> /dev/null
+        then
+           echo -e "Please enter your password for that to happen."
+           sudo -k # revoke previously cached sudo password 
+            if sudo true
+            then 
+                echo -e "Running Script: ${sname} $version"
+            else 
+                echo -e "$redback ----------- This script is made to use 'sudo' ----------- $resetvid"
+                echo -e "$redback ---- Password was incorrect for sudo elevated rights. --- $resetvid"
+                echo -e "Continuing to run the script, but: Expect errors. "
+                Pause
+                echo -e "Running Script: ${sname} $version"
+                #exit_code=107
+                #exit $exit_code
+            fi
+        else
+            echo -e "$redback ----------- This script is made to use 'sudo' ----------- $resetvid"
+            echo -e "$redback        This system does not have 'sudo' installed.        $resetvid"
+            echo -e "$redback If you install 'sudo' you will get much more information. $resetvid"
+            Pause
+            echo -e "Running Script: ${sname} $version"
         fi
     fi
 }
@@ -1646,33 +1664,29 @@ function GetWhere()
 function LocalOrSsh()
 {
     debug "LocalOrSsh:" 1
-    script_progname="${0##*/}"
     message_tmpstr="locally"
-    los_pts=$(ps -e|grep -e "${0##*/}" | grep -om1 'pts/[0-9]*')
-    debug "pts=$los_pts" 1
-    test1=$(ps -e | grep -e '$script_progname' )
-    debug "$test1" 1
-    pidsi=$(ps -e | \
-        grep -m1 -e "$script_progname" | \
-        sed -e 's/^ *//' \
-            -e 's/ .*//' )
-    treestr=$(pstree -A -p -s $pidsi)
+    pidsi="$$"
+    debug "pidsi=$pidsi" 1
+    treestr=$(pstree -A -p -l -s $pidsi)
     debug "$treestr" 1
-    test2=$(echo $treestr | sed -e 's/.*sshd/sshd/' -e 's/${script_progname}($pidsi).*/${script_progname}($pidsi)/' )
-    debug "$test2" 1
-    if [ "$los_pts" != "" ]
+    debug "" 1
+    debug "-------- ^ whole treestr ^ -------- v trimmed treestr v --------" 1
+    treetrm=$(echo $treestr | \
+        sed -e "s/.*sshd/sshd/" | \
+        sed -e "s/($pidsi).*/($pidsi)/")
+    debug "$treetrm" 1
+    treestr_test=$(echo "$treestr" | \
+        grep 'sshd')
+    debug "$treestr_test" 1
+    if [[ "$treestr_test" != "" ]]
     then
-        test3=$(echo "$treestr" | grep 'sshd')
-        debug "$test3" 1
-        if echo "$treestr" | grep 'sshd' > /dev/null
-        then
-            message_tmpstr="via ssh"
-        fi
-    fi
+        message_tmpstr="via ssh"
+     fi
 
-    echo "The 'system-info' script seems to be running $message_tmpstr"
-    nl
-    unset -v script_progname message_tmpstr los_pts pidsi treestr treestr_sshd_test
+     debug "$message_tmpstr" 1
+     echo "The 'system-info' script seems to be running $message_tmpstr"
+     nl
+     unset -v message_tmpstr pidsi treestr treetrm treestr_test
 }
 
 function GetLocal 
